### ISSUE TITLE
癞子数不够却能胡牌

### ISSUE THREAD

**Issue by okou19900722** [yuanfengyun/qipai#10]
`int[] cards = new int[]{ `
`0, 0, 4, 1, 0, 0, 0, 0, 0, /* 万 */ `
`0, 0, 0, 1, 0, 0, 0, 0, 0, /* 筒 */`
`0, 0, 0, 1, 0, 0, 0, 0, 0, /* 条 */`
`0, 0, 0, 1, 0, 0, 0 };//字`
这个牌，字牌只能要一个癞子做将，然后其他的牌型，每个都需要2个癞才能成顺子，但除了check_probability里有减去万字需要的癞子外check_probability_sub里面每次循环找下一个牌型时，没有把当前可能需要的癞子扣除，所以导致这个牌型的结果是可胡牌

**Comment by yuanfengyun** [comment]
什么版本的？

**Comment by okou19900722** [comment]
最新版啊，昨天刚下的

**Comment by okou19900722** [comment]
刚看了下js的代码，是有处理的，java版的代码没有处理

**Comment by yuanfengyun** [comment]
我改下。
