### ISSUE TITLE
请问c++版本是不是不维护了

### ISSUE THREAD

**Issue by can2apple** [yuanfengyun/qipai#12]
我编译了一下发现一些错误 比如 TableMgr::get_instance() 但TableMgr 并无此声明和定义？

**Comment by yuanfengyun** [comment]
还在维护，近期代码改动比较多

**Comment by can2apple** [comment]
请问一下 GetHuInfo(cards []int, cur_card int, gui_1 int, gui_2 int)中的cur_card参数有什么用？gen_feng_table和gen_table有什么区别捏？

**Comment by yuanfengyun** [comment]
cur_card表示第14张牌，如果手牌数是3*n+2张，则不需要第14张牌。gen_feng_table是用来生成字牌表（东南西北中发白)

**Comment by can2apple** [comment]
详细看了下代码，受益匪浅，非常感谢了。
