### ISSUE TITLE
lua算法胡牌验证没问题 但是有些不能胡的也返回的是胡

### ISSUE THREAD

**Issue by kkbjbj** [yuanfengyun/qipai#13]
{0,0,0,0,0,0,0,0,2,0,0,1,1,1,0,0,2,0,2,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,}
9万9万3筒4筒5筒8筒8筒1条1条5条6条7条8条9条
这个验证胡了

**Comment by yuanfengyun** [comment]
哪个版本的？

**Comment by kkbjbj** [comment]
base

**Comment by kkbjbj** [comment]
其它你也验证下吧
