### ISSUE TITLE
请教JS代码中的ProbabilityItemTable含义

### ISSUE THREAD

**Issue by liaolunhui** [yuanfengyun/qipai#17]
研究了一下代码，有点疑惑，求解答
![image](https://user-images.githubusercontent.com/13741751/30846606-e4184e90-a2ca-11e7-9107-bc393dccaa04.png)

**Comment by yuanfengyun** [comment]
代表每种花色有几种赖子分配的可能性。

**Comment by liaolunhui** [comment]
请问每种花色最多5种癞子分配的可能性吗？
假设手牌有8个癞子，不是0-8个癞子的9种分配可能吗？

**Comment by yuanfengyun** [comment]
代码的问题，如果最多是8个赖子，这个数字要改成9，表示0-8个赖子。
