### ISSUE TITLE
lua 新鬼牌版本 检查 吃 将 有问题，导致胡牌判断错误

### ISSUE THREAD

**Issue by luoqeng** [yuanfengyun/qipai#21]

**Comment by yuanfengyun** [comment]
哪个文件？

**Comment by luoqeng** [comment]
gui_table/hulib.lua 
function M.get_need_gui

**Comment by yuanfengyun** [comment]
测试牌型是怎么样的？

**Comment by luoqeng** [comment]
local t = {
        0,0,0,   0,0,3,   0,0,0,
        0,0,0,   3,0,0,   0,0,0,
        1,1,1,   1,1,1,   2,0,0,
        0,0,0,0, 0,0,0}

随便一个有吃的就行

function M.check(cards, gui_num)
	local total_need_gui = 0
	local eye_num = 0
	for i=0,3 do
		local from = i*9 + 1
		local to = from + 8
		if i == 3 then
			to = from + 6
		end
		
               -- i == 3 就代表吃？
		local need_gui, eye = M.get_need_gui(cards, from, to, **_i==3_**, gui_num)
		if need_gui then
			total_need_gui = total_need_gui + need_gui
		end
		if eye then
			eye_num = eye_num + 1
		end
	end
	
	if eye_num == 0 then
		return total_need_gui + 2 <= gui_num
	elseif eye_num == 1 then
		return total_need_gui <= gui_num
	elseif
		return total_need_gui + eye_num - 1 <= gui_num
	end
end

function M.get_need_gui(cards, from, to, **_chi_**, gui_num)
	local **_num_** = 0
	local key = 0
	for i=from,to do
		key = key * 10 + cards[i]
	end

    for i=0, gui_num do
        -- num 一直为0，num应该是指这组牌的数量吧。
        local yu = (**_num_** + i)%3
        if yu ~= 1 then
            -- 多余两张就代表将？ 如果是连续两张呢？会般判断有误吧。
            local eye = (yu == 2)
            if table_mgr:check(key, i, eye, **_chi_**) then
                return i, eye
            end
        end
    end
end

**Comment by luoqeng** [comment]
随便一个有吃的牌型就行

    local t = {
        0,0,0,   0,0,3,   0,0,0,
        0,0,0,   3,0,0,   0,0,0,
        1,1,1,   1,1,1,   0,2,0,
        0,0,0,0, 0,0,0}

**Comment by liufangmeng** [comment]
为什么这样表示牌？ 看不懂
int[] cards = { 
			0, 0, 0, 1, 1, 1, 0, 0, 0, /* 万 */ 
			1, 1, 1, 0, 0, 0, 0, 0, 0, /* 筒 */
			2, 0, 0, 0, 0, 0, 0, 0, 0, /* 条 */
			0, 0, 0, 0, 0, 0, 0 };//字

**Comment by yuanfengyun** [comment]
已改
