### ISSUE TITLE
c++版本的split和split2拆分法有问题

### ISSUE THREAD

**Issue by zhaobu** [yuanfengyun/qipai#22]
c++版本的split和split2拆分法有问题.我试过查表版和HuPaiMj3.h,HuPaiMj2.h,还有拆分法,并且把我自己用的胡牌算法代进去,900万次,发现拆分法的结果不对,总会比其他的算法得出的少一些,并且拆分法的性能不是最好的

**Comment by yuanfengyun** [comment]
已修正
