### ISSUE TITLE
golang下计算算法耗时的有出入

### ISSUE THREAD

**Issue by orz54748674** [yuanfengyun/qipai#25]
在GetHuInfo里，var tmp_cards = cards并非深拷贝，因为cards不是数组，而是切片，所以这边只是引用，然后这样导致每次循环cards已经被改变了，在list_probability里的ptbl.m_num[anum] <= 0每次都成立，都没走到最耗时的鬼牌组合的函数里check_probability，如此计算最终耗时是5秒没错，go test下测试。
但是，经过把上面的引用改为正确的深拷贝后（比较耗时的操作
var tmp_cards = make([]int, len(cards))
copy(tmp_cards , cards)
），鬼牌2张，总麻将数17张，结果是35秒。

**Comment by yuanfengyun** [comment]
处理手法并不是你这样弄的。

**Comment by orz54748674** [comment]
我说的哪里不对吗？

**Comment by orz54748674** [comment]
`func test_time(count int) {
	cards := []int{
		0, 0, 0, 2, 0, 0, 1, 0, 0,
		1, 1, 1, 0, 0, 3, 2, 0, 2,
		0, 3, 0, 0, 0, 0, 0, 0, 0,
		0, 0, 0, 0, 0, 0, 0,
	}

    start := time.Now().Unix()
    for i:=0;i<count;i++{
        mjlib.MHuLib.GetHuInfo(cards, 7, 3, 34)
        if i == 99999999 {
        	print_cards(cards)
		}
    }
    fmt.Println("count=",count,"use time=",time.Now().Unix()-start)
}`

**Comment by orz54748674** [comment]
test hulib begin...
0,0,0,0,0,0,1,100000000,0,
1,1,1,0,0,3,2,0,2,
0,3,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,
count= 100000000 use time= 5

Process finished with exit code 0

**Comment by yuanfengyun** [comment]
更新代码，再测试。

**Comment by orz54748674** [comment]
一种鬼牌，3只鬼的情况下，耗时差不多12秒
count= 100000000 use time= 12
算法本身很好，速度这样子也是蛮快的
