### ISSUE TITLE
到底哪个语言版本是最ok的？

### ISSUE THREAD

**Issue by liufangmeng** [yuanfengyun/qipai#28]

**Comment by yuanfengyun** [comment]
每个版本都是OK的，但不是无脑就可以用的。你至少先读几天代码吧。

**Comment by liufangmeng** [comment]
之前一直看java，结果过了几天 大更新 都搞不懂了

**Comment by yuanfengyun** [comment]
只是调整了目录，新增了一种拆分的算法。

**Comment by liufangmeng** [comment]
大神你好，这个是java新增的拆分法，有点不懂 特来请教：
2个方法：test_success和test_fail  
第一个test_success，里面调用 split.get_hu_info(cards, 34, 33) ，参数 33是指最后的2个白板做百搭，可以胡牌。
但是 第二个方法 test_fail 不管是否百搭 都胡不了啊，为什么还是输出了：test success
下面是2个方法
	`public static void test_success() {
		int[] cards = {
			1,1,0,0,1,0,1,0,0,
			0,0,0,2,4,2,0,0,0,
			0,0,0,0,0,0,0,0,0,
			0,0,0,0,0,0,2
		};
		
		if(split.get_hu_info(cards, 34, 33)){
			System.out.println("test success"); 
		}
	}
	
	public static void test_fail() {
		int[] cards = {
			1,1,0,0,1,0,1,0,0,
			0,0,0,2,4,2,1,0,0,
			0,0,0,0,0,0,0,0,0,
			0,0,0,0,0,0,1
		};
		
		if(!split.get_hu_info(cards, 34, 33)){
			System.out.println("test success"); 
		}
	}`

**Comment by yuanfengyun** [comment]
本身就是用来测试不能胡的，小伙子，你能不能读读函数名。这牌型本身就是胡不了，用来测试算法会不会把不能胡的牌判断成胡。

**Comment by liufangmeng** [comment]
︽⊙＿⊙︽ 
原来是这样。。。我以为输出的test success  就是胡了呢。。。
