### ISSUE TITLE
lua的算法似乎忽略了某些情况

### ISSUE THREAD

**Issue by clipon** [yuanfengyun/qipai#29]
我使用qipai/mjlib_lua/gui_table麻将算法遇到了问题：

local t = {
        0,0,0,   0,0,3,   0,0,0,
        0,0,0,   3,0,0,   1,1,1,
        0,0,0,   1,1,1,   0,0,2,
        0,0,0,0, 0,0,0}
    hulib.get_hu_info(t, 0) 

这样的结果居然是失败的，真奇怪

local t = {
        0,0,0,   0,0,3,   0,0,0,
        0,0,0,   3,0,0,   1,1,1,
        0,0,0,   1,1,1,   0,0,0,
        0,0,0,0, 2,0,0}
    hulib.get_hu_info(t, 32)
这样是成功的

local t = {
        0,0,0,   0,0,3,   0,0,0,
        0,0,0,   3,0,0,   1,1,1,
        0,0,0,   1,1,1,   0,0,1,
        0,0,0,0, 1,0,0}
    hulib.get_hu_info(t, 32)
这样也是失败的

**Comment by clipon** [comment]
找到原因了，hulib里边有两处bug

**Comment by yuanfengyun** [comment]
看样子你是看懂了。修改上传了。

**Comment by clipon** [comment]
也是被逼的，自己又写不出算法，只好帮你改bug
