### ISSUE TITLE
拆分法出现不能胡牌的状况

### ISSUE THREAD

**Issue by PolarSnow** [yuanfengyun/qipai#30]
牌型数组如下，鬼牌为 cards[14]
`    char cards[34] = { 
        0,0,1, 1,1,0, 0,0,0, 
        0,2,1, 2,0,1, 0,0,0, 
        1,1,1, 0,0,0, 0,2,0, 
        0,0,0, 0,0,0, 0
    };`
使用的算法为
qipai/mjlib_c++/split/
另外当牌型为如下时是可以通过的
`    char cards[34] = { 
        0,0,0, 1,1,0, 0,0,0, 
        0,2,2, 2,0,1, 0,0,0, 
        1,1,1, 0,0,0, 0,2,0, 
        0,0,0, 0,0,0, 0
    };`

**Comment by yuanfengyun** [comment]
已改。
