### ISSUE TITLE
c++版本split胡77789万判断出错

### ISSUE THREAD

**Issue by intgogo** [yuanfengyun/qipai#31]
7 7 7 8 9 万 判断出来是不胡的...大哥能帮忙看下吗？哈哈

**Comment by intgogo** [comment]
我用的c++ split2版本～

**Comment by yuanfengyun** [comment]
你调试下。

**Comment by intgogo** [comment]
兄弟啊...好多BUG啊，c++版本是没法用的 - -

**Comment by yuanfengyun** [comment]
你这是几天了还没学会怎么用啊。
        char cards[] = {
		0,0,0,0,0,0,3,1,1,
		0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0
	};
	int hu = split2::get_hu_info(cards, 34, 34);

	cout << "hu:" << hu << endl;
        我这里都是能胡，你别乱瞎测，瞎说啊。

**Comment by intgogo** [comment]
兄弟啊，你确定你那边打印出来的是胡的？我这边的结果就是不胡啊。。。
