### ISSUE TITLE
cpp splite2

### ISSUE THREAD

**Issue by yangxingpping** [yuanfengyun/qipai#43]
在windows下跑test_split2时调用到
hu += split2::get_hu_info(&source[n * 34], 34, gui_index);
时 当n=1时，在函数
split2::one(char* cards, int& index, int& need_gui, int max_gui, int used_gui)
时会出现index=9,而cards数组的长度为9,此时要执行访问了cards[9],cards[10]
int c1 = cards[index];
int c2 = cards[index+1];
并执行了操作
cards[index]--;   //cards[9]--;
,访问越界。

**Comment by yuanfengyun** [comment]
你改一下，提个pr
