### ISSUE TITLE
算法支持其中一种 只有100张的广东麻将吗？

### ISSUE THREAD

**Issue by wuchujiecode** [yuanfengyun/qipai#44]
请问支持广东麻将100只 (条子，筒子，翻子) 吗。
为什么python算法里面 
if cur_card != 34:
        cards[cur_card] = cards[cur_card] + 1
这个是有什么作用

**Comment by yuanfengyun** [comment]
慢慢读代码，自然能弄懂你的问题。

**Comment by wuchujiecode** [comment]
首先非常谢谢开源分享。再慢慢读算法，主要是我们这边打100只。。思路暂时转不过来。哈哈。非常感谢
