### ISSUE TITLE
c++龙七对判断出错

### ISSUE THREAD

**Issue by kebiaoy** [yuanfengyun/qipai#50]
char cards[] = {
		4,0,2,0,2,0,2,2,2,
		0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0,0,0,
		0,0,0,0,0,0,0
	};
bool isHu = split2::get_hu_info(cards,34, 33);
没有用到鬼牌，这个牌应该是龙7对，该判胡才对。

**Comment by yuanfengyun** [comment]
只判断基本胡牌牌型。特殊牌型是由特殊代码单独判断。
