### ISSUE TITLE
lua拆分法字牌问题

### ISSUE THREAD

**Issue by Tatamethues** [yuanfengyun/qipai#52]
字牌如果是4,2,0,0,0,0,0的情况是有将的，为什么拆分法看到4直接return false是不是有问题？

**Comment by yuanfengyun** [comment]
你先熟悉熟悉麻将的规则。

**Comment by Tatamethues** [comment]
不好意思，搞错了-。-秀逗了刚才，以为只是在检查有没有将。忘了总体是检测能不能胡了。
