### ISSUE TITLE
查表法，求出带眼的组合的问题。

### ISSUE THREAD

**Issue by iamjokerjun** [yuanfengyun/qipai#53]
请教下。gen_eye_table 函数中，
local function gen_eye_table()
    local t = {0,0,0,0,0,0,0,0,0}

    for i=1,18 do
        t[i] = 2
        print("将",i)
        add_to_table(t)
        gen_table_sub(t, 1)
        t[i] = 0
    end
end

这个18 如何理解？不是应该只有9就行了么

**Comment by yuanfengyun** [comment]
对，应该是9
